version: '3.7'
services:
    postgres:
        image: postgres:12.0
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        networks:
          - airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
          - airflow_pg:/var/lib/postgresql/data/

    webserver:
        #build:
        #    context: ./
        image: itzblend/huhta-airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__CORE__FERNET_KEY='5_2kb-OYOdS3-B97idfhYMqAIBZHb0NW1Z-M3BuLOnQ='
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ../../../:/usr/local/airflow/dags
            - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg
        networks:
          - airflow
        ports:
            - "8882:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

networks:
  airflow:
    driver: bridge

volumes:
  airflow_pg:
